version: "3.9"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-server
    ports:
      - "8080:8080"

  database:
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_USER: graalvm-demo
      POSTGRES_PASSWORD: "Postgr@s321!"
    ports:
      - "5432:5432"
  www.auth-server.com:
    image: "ghcr.io/digissance/graalvm-demo:${TAG}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/graalvm-demo
      SPRING_DATASOURCE_USERNAME: graalvm-demo
      SPRING_DATASOURCE_PASSWORD: "Postgr@s321!"
      SPRING_PROFILES_ACTIVE: dev
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
#    ports:
#      - "8080:8080"
    depends_on:
      - database
