apiVersion: v1
kind: Service
metadata:
  name: {{ include "graalvm-demo.fullname" . }}
  labels:
    {{- include "graalvm-demo.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graalvm-demo.selectorLabels" . | nindent 4 }}
