logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graalvm-demo
    username: graalvm-demo
    password: 'Postgr@s321!'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true