logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/graalvm-demo}
    username: ${SPRING_DATASOURCE_USERNAME:graalvm-demo}
    password: ${SPRING_DATASOURCE_PASSWORD:Postgr@s321!}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true