logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  datasource:
    generate-unique-name: false
    name: testdb
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    password: SA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true